# **TEST 2.0**

Python Questions

In [38]:
#1) Write a Python program using lambda to calculate the square of a number entered by the user

In [39]:
#ans)
#lambda function is anonymous functions that can take any number of arguments.It is defined using lambda keyword

square=lambda x:x**2
a=square(5)
b=square(4)
print(f'square of 5 is {a}')
print(f'square of 4 is {b}')

square of 5 is 25
square of 4 is 16


In [165]:
#2) Use map to double all the elements in the list: [1, 2, 3, 4, 5]


In [169]:
import builtins

In [171]:
#ans)

#map function is used when we want to apply single transformation to all iteratable elements
values=[1,2,3,4,5]
double=builtins.list(map(lambda x:x*2,values))
print(double)

[2, 4, 6, 8, 10]


In [172]:
#3)Use filter to extract all even numbers from the list: [10, 15, 20, 25, 30].


In [175]:
import builtins

In [177]:
#ans)
#filter function is used to filtering a sequence based on the specific conditions
Items=[10,15,20,25,30]
even=builtins.list(filter(lambda x:x%2==0,Items))
print(even)


[10, 20, 30]


In [151]:
#4) Write a one-liner lambda function to check if a given number is a palindrome

In [154]:
#ans)
is_palindrome = lambda num: str(num) == str(num)[::-1]
is_palindrome(121)


True

In [77]:
#6)Write a function that uses **kwargs to accept a student’s details (name, age, and grade) and print them in a formatted string.

In [87]:
#ans)
def print_student_details(**kwargs):
  name = kwargs.get('name', 'Unknown')
  age = kwargs.get('age', 'N/A')
  grade = kwargs.get('grade', 'N/A')

  # Printing the student details inside the function
  print(f"Student Name: {name}") # Moved print statements inside the function
  print(f"Age: {age}")
  print(f"Grade: {grade}")

# Calling the function with student details
print_student_details(name="Appu", age=18, grade="A")

Student Name: Appu
Age: 18
Grade: A


In [157]:
#7) Create a class Person with attributes name and age. Add a method greet that prints a greeting with the name.
#Create an object of the class and call the greet method.


In [159]:
#ans)
class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age

  def greet(self):
    print(f"Hello, my name is {self.name} and I am {self.age} years old.")

In [160]:
#8)Create a base class Animal with a method speak that prints "I am an animal."
#Create a derived class Dog that overrides the speak method to print "I am a
#dog.

In [161]:
#ans)
class Animal:
  def speak(self):
    print("I am an animal.")

class Dog(Animal):
  def speak(self):
    print("I am a dog.")


In [60]:
#10)Write a program to print the first 10 natural numbers using a for loop

In [65]:
#ans)
for i in range(0,11):
  print(i)

0
1
2
3
4
5
6
7
8
9
10


In [48]:
#11)Write a program to calculate the sum of all numbers in a list: [5, 10, 15, 20] using a for loop

In [46]:
#ans)
#for llop is used to iterating over a sequence which may be a list,tuple,dictionary,set or a string
sum=0
list=[5,10,15,20]
for i in list:
    sum=sum+i
print(sum)

50


In [ ]:
#12)Write a Python program to print the multiplication table of a given number using a while loop.

In [45]:
#ans)
# In while loop we can execute a set of statements as long as the condition is true
num=int(input('enter a number'))
i=1
while i<=10:
  print(f"{num} x {i} = {num * i}")
  i=i+1


enter a number6
6 x 1 = 6
6 x 2 = 12
6 x 3 = 18
6 x 4 = 24
6 x 5 = 30
6 x 6 = 36
6 x 7 = 42
6 x 8 = 48
6 x 9 = 54
6 x 10 = 60


In [42]:
#14)Write a Python program to check if a number entered by the user is even or odd

In [44]:
#ans)
num=int(input('enter a number'))
if num%2==0:
    print(f'{num} is even')
else:
    print(f'{num} is odd')

enter a number6
6 is even


In [50]:
#15).Write a Python program to determine the grade of a student based on their marks:
#• Marks >= 90: Grade A
#• Marks >= 75: Grade B
#• Marks >= 50: Grade C
#• Otherwise: Grade F

In [49]:
#ans)
#we can use input  for entering a value ,incase of integers we can use int with this.
#if statement is the most basic conditional statement.The elif statement is usec to check the additional conditions if the preceding if is false
marks=int(input('enter your marks'))
if marks>=90:
    print('Grade A')
elif marks>=75:
    print('Grade B')
elif marks>=50:
    print('Grade C')
else:
    print('Grade F')

enter your marks8
Grade F


In [ ]:
#19)Write a Python program to reverse a string using a for loop.

In [58]:
#ans)
string=input('enter a string')
reverse=''
for i in string:
    reverse=i+reverse
print(reverse)

enter a stringhi
ih


In [164]:
#20)Write a Python program to count the number of vowels in a string entered by the user.

In [163]:
#ans)
string=input('enter a string')
count=0
for i in string:
    if i in 'aeiouAEIOU':
        count=count+1
print(count)

enter a stringkitty
1


Numpy Questions

In [90]:
import numpy as np


In [92]:
#Numpy is a python library for numerical data processing

In [88]:
#1) Create a NumPy array of zeros with shape (3, 4).

In [94]:
#ans)
print("vector of zeros \n---------")
print(np.zeros([3,4]))

vector of zeros 
---------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [93]:
#2) Create a NumPy array of ones with shape (2, 5).

In [95]:
#ans)
print("vector of ones \n------------")
print(np.ones([2,5]))

vector of ones 
------------
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [96]:
#3) Create a NumPy matrix with the values from 1 to 10 using np.arange().


In [98]:
#ans)
x=np.arange(1,11).reshape(2,5)
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [99]:
#4)Create a NumPy array with numbers from 0 to 1 (inclusive) with a step size of 0.1  using np.arange()

In [102]:
#ans)
y=np.arange(0,1,0.1)
y


array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [103]:
#5) Create a NumPy array with 10 equally spaced values between 0 and 1 using np.linspace() with endpoint=False.


In [117]:
#ans)
#linspace is very useful for generating a specified number of evenly spaced points between a given range
z=np.linspace(0,1,10,endpoint=False)
z


array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [118]:
#6) Write a NumPy program to compute the square root of each element in the array [1, 4, 9, 16].
#square root of a function is finding using the function sqrt

In [106]:
#ans)
a=np.array([1,4,9,16])
np.sqrt(a)

array([1., 2., 3., 4.])

In [107]:
#7) Compute the sum of all elements in the array np.array([2, 3, 4, 5, 6])


In [119]:
#ans)
#sum() function is used for finding sum of sequence
b=np.array([2,3,4,5,6])
np.sum(b)

20

In [109]:
#8) Find the minimum value in the array np.array([1, 5, 9, 3, 6]) using np.min().

In [110]:
#ans)
#using np.min() we can calculate  minimum of a sequence
c=np.array([1,5,9,3,6])
np.min(c)

1

In [111]:
#9)Find the maximum value in the array np.array([1, 5, 9, 3, 6]) using np.max().


In [120]:
#ans)
#np.max is used for calculating the maximum of a sequence
d=np.array([1,5,9,3,6])
np.max(d)

9

In [113]:
#10)Use np.ceil() to round the elements of the array np.array([1.2, 2.5, 3.7, 4.9]) to the nearest greater integer.


In [121]:
#ans)
#ceil() function is used for rounding off decimal to nearest integer
e=np.array([1.2,2.5,3.7,4.9])
np.ceil(e)

array([2., 3., 4., 5.])

In [115]:
#11)Generate an array of 5 random integers between 10 and 50 using np.random.randint()

In [122]:
#ans)
#np.random.randint() is used for generating random integers
f=np.random.randint(10,50,5)
f


array([13, 48, 13, 13, 18])

In [123]:
#12)Generate an array of 5 random floating-point numbers between 0 and 1 using np.random.rand().

In [124]:
#ans)
#np.random.rand() is used for generating random floating point numbers
g=np.random.rand(5)
g


array([0.29118502, 0.38365895, 0.35123255, 0.27426795, 0.69328156])

In [126]:
#13)Generate a 3x3 matrix of random numbers from a normal distribution with mean 0 and standard deviation 1 using np.random.randn().


In [131]:
#ans)
#random.randn() is used for generating random numbers from a normal distribution
c=np.random.randn(3,3)
print('matrix','\n',c)



matrix 
 [[ 0.29339455 -0.08396164 -0.99030724]
 [-0.511256    0.09066385 -0.22718146]
 [ 0.08845034 -1.47470181  2.33601864]]


In [133]:
#14)Use np.where() to replace all elements greater than 5 in the array [1, 2, 3, 6, 7, 8] with 10

In [136]:
#ans)
#np.where is used for finding the index of a condition
list=np.array([1,2,3,6,7,8])
np.where((list)>5,10,list)



array([ 1,  2,  3, 10, 10, 10])

In [138]:
#15)Use np.where() to find the index of the first element that is greater than 3 in the array [1, 2, 3, 4, 5].

In [139]:
#ans)
list=np.array([1,2,3,4,5])
np.where(list>3)


(array([3, 4]),)

In [140]:
#16).Perform matrix addition of two matrices A = np.array([[1, 2], [3, 4]]) and B = np.array([[5, 6], [7, 8]])

In [141]:
#ans)
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print(A+B)

[[ 6  8]
 [10 12]]


In [142]:
#17)Perform element-wise matrix division of matrix A = np.array([[1, 2], [3, 4]]) by matrix B = np.array([[5, 6], [7, 8]]).

In [143]:
#ans)
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print(A/B)


[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [144]:
#18)Perform matrix multiplication of matrices A = np.array([[1, 2], [3, 4]]) and B = np.array([[5, 6], [7, 8]]).

In [145]:
#ans)
h=np.array([[1,2],[3,4]])
i=np.array([[5,6],[7,8]])
print(np.dot(h,i))
#

[[19 22]
 [43 50]]


In [146]:
#19)Reshape a 1D array [1, 2, 3, 4, 5, 6] into a 2x3 matrix using np.reshape()

In [148]:
#ans)
#np.reshape is used  for reshaping a given array
j=np.array([1,2,3,4,5,6])
print(np.reshape(j,(2,3)))

[[1 2 3]
 [4 5 6]]


In [149]:
#20)Slice the first two elements from the array np.array([10, 20, 30, 40, 50])

In [150]:
#ans)
#we can perform slicing in an array based on the index
k=np.array([10,20,30,40,50])
print(k[0:2])


[10 20]
